test_that(desc = "ExactOnline", {
  result <- read_xaf("ExactOnline.xaf")
  expect_equal(nrow(result), 167)
  expect_equal(ncol(result), 22)
  sub <- xaf_subtables(result)
  expect_equal(length(sub), 4)
  balance <- xaf_balance_sheet(result)
  expect_equal(nrow(balance), 24)
  income <- xaf_income_statement(result)
  expect_equal(nrow(income), 20)
})

test_that(desc = "osFinancials", {
  result <- read_xaf("osFinancials.xaf")
  expect_equal(nrow(result), 10)
  expect_equal(ncol(result), 22)
  sub <- xaf_subtables(result)
  expect_equal(length(sub), 4)
  balance <- xaf_balance_sheet(result)
  expect_equal(nrow(balance), 9)
  income <- xaf_income_statement(result)
  expect_equal(nrow(income), 2)
})

test_that(desc = "AFAS", {
  result <- read_xaf("AFAS.xaf")
  expect_equal(nrow(result), 31309)
  expect_equal(ncol(result), 22)
  sub <- xaf_subtables(result)
  expect_equal(length(sub), 4)
  balance <- xaf_balance_sheet(result)
  expect_equal(nrow(balance), 49)
  income <- xaf_income_statement(result)
  expect_equal(nrow(income), 83)
})

test_that(desc = "Twinfield", {
  result <- read_xaf("Twinfield.xaf")
  expect_equal(nrow(result), 181)
  expect_equal(ncol(result), 22)
  sub <- xaf_subtables(result)
  expect_equal(length(sub), 4)
  balance <- xaf_balance_sheet(result)
  expect_equal(nrow(balance), 32)
  income <- xaf_income_statement(result)
  expect_equal(nrow(income), 24)
})

test_that(desc = "Multivers", {
  result <- read_xaf("Multivers.xaf")
  expect_equal(nrow(result), 371)
  expect_equal(ncol(result), 22)
  sub <- xaf_subtables(result)
  expect_equal(length(sub), 4)
  balance <- xaf_balance_sheet(result)
  expect_equal(nrow(balance), 43)
  income <- xaf_income_statement(result)
  expect_equal(nrow(income), 20)
})
